#!/usr/bin/bash

OSTAP_SOURCE=${1}

if [[ -d $ROOTSYS ]]
then
    echo 'ROOTSYS directory:' $ROOTSYS     
else 
    echo 'No ROOTSYS directory:' $ROOTSYS 
    return 3
fi

if [[ $OSTAP_SOURCE                &&
      -d $OSTAP_SOURCE             &&
      -d $OSTAP_SOURCE/ostap       &&
      -d $OSTAP_SOURCE/source      &&
      -d $OSTAP_SOURCE/scripts     &&
      -d $OSTAP_SOURCE/examples    &&
      -d $OSTAP_SOURCE/data        &&
      -f $OSTAP_SOURCE/CMakeLists.txt ]]
then  	 
  true
else 	
  echo 'No valid source directory is found!' $OSTAP_SOURCE 
  return 1 
fi

OSTAP_BUILD=${2:-$OSTAP_SOURCE/build}

if [[ $OSTAP_BUILD && -d $OSTAP_BUILD && -w $OSTAP_BUILD ]]
then
    true
elif [[ -w $OSTAP_SOURCE ]]
then 
    mkdir $OSTAP_SOURCE/build
    OSTAP_BUILD=$OSTAP_SOURCE/build  
    echo 'Build directory is created' $OSTAP_BUILD
else
    OSTAP_BUILD=`mktemp -d -t ostap-$(date '+%Y-%b-%d')-OSTAP-BUILD-DIR-XXXXXX`
    echo 'Build directory is created' $OSTAP_BUILD
fi 


OSTAP_INSTALL=${3:-$OSTAP_BUILD/INSTALL}

if [[ -f $OSTAP_BUILD/build.ninja ]]
then
 ( echo '[1/6] CLEAN REMNANTS'             ; cd $OSTAP_BUILD ; pwd ; ninja clean )
fi
(  echo '[2/6] REMOVE REMNANTS & GARBAGE'  ; cd $OSTAP_BUILD ; pwd ; rm -rfv $OSTAP_INSTALL CM* CP* CT* *nin* scripts/ source/ ostap/ examples/ Testing/ Ma* .nin* Dart* cmake* instal* Tes* *.py~ *.C~ __* _CPa* \#* *~ .*~ .\#*  )
(  echo '[3/6] FIRST  PASS OF CMAKE+NINJA' ; cd $OSTAP_BUILD ; pwd ; cmake $OSTAP_SOURCE -DCMAKE_INSTALL_PREFIX=$OSTAP_INSTALL -G Ninja ; ninja ; ninja install | grep -v Up-to-date )
(  echo '[4/6] SECOND PASS OF CMAKE+NINJA' ; cd $OSTAP_BUILD ; pwd ; cmake $OSTAP_SOURCE -DCMAKE_INSTALL_PREFIX=$OSTAP_INSTALL -G Ninja ; ninja ; ninja install | grep -v Up-to-date )

if [[ -f $OSTAP_INSTALL/thisostap.sh &&
      -x $OSTAP_INSTALL/thisostap.sh ]]
then
  source $OSTAP_INSTALL/thisostap.sh
else 
  echo 'No thisostap.sh is found!' $OSTAP_INSTALL/thisostap.sh 
  return 4 
fi

(  echo '[5/6] THIRD  PASS OF CMAKE+NINJA' ; cd $OSTAP_BUILD ; pwd ; cmake $OSTAP_SOURCE -DCMAKE_INSTALL_PREFIX=$OSTAP_INSTALL -G Ninja ; ninja ; ninja install | grep -v Up-to-date )
(  echo '[6/6] LAST   PASS OF NINJA'       ; cd $OSTAP_BUILD ; pwd ; cmake $OSTAP_SOURCE -DCMAKE_INSTALL_PREFIX=$OSTAP_INSTALL -G Ninja ; ninja ; ninja install | grep -v Up-to-date )

echo 'OSTAP_SOURCE  :' $OSTAP_SOURCE
echo 'OSTAP_BUILD   :' $OSTAP_BUILD
echo 'OSTAP_INSTALL :' $OSTAP_INSTALL
echo 'OSTAPDIR      :' $OSTAPDIR
echo 'ROOTSYS       :' $ROOTSYS
echo 'PYTHON        :' `python --version`
echo 'python        :' `which python`
echo 'root.exe      :' `which root.exe`
echo 'ostap         :' `which ostap`
