#!/usr/bin/env bash
LCG=$1
CMTCONFIG=$2

mkdir build
cd    build

## OLD 
## source /cvmfs/sft.cern.ch/lcg/views/${LCG}/${CMTCONFIG}/setup.sh
## cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/ -GNinja && ninja && ninja install

## source /cvmfs/sft.cern.ch/lcg/views/${LCG}/${CMTCONFIG}/setup.sh
source ../.aux/.build-lcg ${LCG} ${CMTCONFIG}

echo 'BUILD-WITH-LCG:     python ' $(which python)
echo 'BUILD-WITH-LCG:     python ' $(python --versino)

user_site=$(python -m site --user-site)
if [[ ${user_site} && -d ${user_site} ]]
then
    echo 'BUILD-WITH-LCG:     USER-SITE directory ' ${user_site}
    ls ${user_site}    
elif [[ ! -d ${user_site}
    echo 'BUILD-WITH-LCG:  no USER-SITE directory ' ${user_site}  
fi

which python

user_site=$(python -m site --user-site)
echo 'USER-SITE python directory: ' ${user_site}
ls -al ${user_site}

if command -v pip &> /dev/null
then
    python -m pip list --user 
fi

## (re)check all dependencies
if command -v check-dependencies  &> /dev/null
then
    check-dependencies 
fi


