#!/usr/bin/bash



OSTAP_CONDA_ENV=${1:-test-env}


conda_path = $(command -v conda)

if   [[ $conda_path && -x $conda_path ]]
then
    true
elif [[ -f $HOME/conda.sh && -x $HOME/conda.sh ]]
     source $HOME/conda.sh
     echo 'OSTAP_SOURCE       : ' $OSTAP_SOURCE   
     echo 'source conda.sh    : ' $HOME/conda.sh 
else
    echo 'Do not know to to access CONDA'
    return 5 
fi 

conda activate $OSTAP_CONDA_ENV

OSTAP_SOURCE=${2:-/teo/user/ibelyaev/ostap}

if [[ $OSTAP_SOURCE                     &&
      -d $OSTAP_SOURCE                  &&
      -d $OSTAP_SOURCE/ostap            &&
      -d $OSTAP_SOURCE/source           &&
      -d $OSTAP_SOURCE/scripts          &&
      -d $OSTAP_SOURCE/examples         &&
      -d $OSTAP_SOURCE/data             &&
      -f $OSTAP_SOURCE/CMakeLists.txt   &&
      -f $OSTAP_SOURCE/.aux/build-ostap && 
      -x $OSTAP_SOURCE/.aux/build-ostap ]]
then
    echo 'OSTAP_SOURCE       : ' $OSTAP_SOURCE   
else
    echo 'No valid source directory is found!' $OSTAP_SOURCE 
    return 5 
fi 

OSTAP_BUILD=${3:-$OSTAP_SOURCE/build}

if   [[ $OSTAP_BUILD && -d $OSTAP_BUILD && -w $OSTAP_BUILD ]]
then
    true
elif [[ -w $OSTAP_SOURCE ]]
then 
    mkdir $OSTAP_SOURCE/build
    OSTAP_BUILD=$OSTAP_SOURCE/build  
    echo 'Build directory is created' $OSTAP_BUILD
else
    OSTAP_BUILD=`mktemp -d -t ostap-$(date '+%Y-%b-%d')-OSTAP-BUILD-DIR-XXXXXX`
    echo 'Build directory is created' $OSTAP_BUILD
fi


if [[ ! -f $OSTAP_BUILD/build-ostap ]]
then
    cp $OSTAP_SOURCE/.aux/build-ostap $OSTAP_BUILD/build-lcg
    echo 'copy build-ostap from  ' $OSTAP_BUILD/.aux/build-ostap
fi

OSTAP_INSTALL=${4:$OSTAP_BUILD/INSTALL/CONDA}

echo 'OSTAP_CONDA_ENV    : ' $OSTAP_CONDA_ENV
echo 'OSTAP_SOURCE       : ' $OSTAP_SOURCE
echo 'OSTAP_BUILD        : ' $OSTAP_BUILD
echo 'OSTAP_INSTALL      : ' $OSTAP_INSTALL

source  $OSTAP_BUILD/build-ostap $OSTAP_SOURCE $OSTAP_BUILD $OSTAP_INSTALL 

