#!/usr/bin/env bash
LCG=$1
CMTCONFIG=$2

echo 'test-with-lcg       LCG =' ${LCG}
echo 'test-with-lcg CMTCONFIG =' ${CMTCONFIG}
echo 'test-with-lcg       PWD =' ${PWD}


cd ./build

if [[ ${LCG}                                                       &&
	  ${CMTCONFIG}                                                 &&                        
	  -f /cvmfs/sft.cern.ch/lcg/views/${LCG}/${CMTCONFIG}/setup.sh &&
	  -f ./INSTALL/${LCG}/${CMTCONFIG}/thisostap.sh                ]]
then
    
    echo 'TEST-WITH-LCG: sourcing ' /cvmfs/sft.cern.ch/lcg/views/${LCG}/${CMTCONFIG}/setup.sh    
    source /cvmfs/sft.cern.ch/lcg/views/${LCG}/${CMTCONFIG}/setup.sh
    
    echo 'TEST-WITH-LCG: sourcing ' ./INSTALL/${LCG}/${CMTCONFIG}/thisostap.sh
    source ./INSTALL/${LCG}/${CMTCONFIG}/thisostap.sh
    
else
    
    echo '(re)source .build-lcg'
    source ../.aux/.build-lcg ${LCG} ${CMTCONFIG}
        
fi

## echo '(re)source .build-lcg'
## source ../.aux/.build-lcg ${LCG} ${CMTCONFIG}

echo 'TEST-WITH-LCG:      python ' $(which python)
echo 'TEST-WITH-LCG:      python ' $(python --version)

## 
user_site=$(python -m site --user-site)
if [[ ${user_site} && -d ${user_site} ]]
then
    echo 'TEST-WITH-LCG:      USER-SITE directory ' ${user_site}
    ls ${user_site}
elif [[ ! -d ${user_site} ]] 
then 
    echo 'TEST-WITH-LCG:   no USER-SITE directory ' ${user_site}  
fi

if command -v pip &> /dev/null
then
    python -m pip list --user
fi
    
## (re)check all dependencies 
COLUMNS=200 check-dependencies

## run tests 
OSTAP_BATCH=True COLUMNS=200 ctest -j4 -R '(gof|rewe)' --output-on-failure --test-output-size-failed 5000000


