#!/usr/bin/env python
# -*- coding: utf-8 -*-
# =============================================================================
## @file ostap/stats/pvalue.py
#  Utilities to get p-values for Two-Samples & Goodness-of-Fit tests
#  using permutations, bootstrap and toys
#  - parallelization is included 
#  @author Vanya BELYAEV Ivan.Belyaev@cern.ch
#  @date   2023-12-06
# =============================================================================
""" Utilities to get p-values for Two-Samples & Goodness-of-Fit tests  
    using permutations, bootstrap and toys 
- parallelization is included 
"""
# =============================================================================
__version__ = "$Revision$"
__author__  = "Vanya BELYAEV Ivan.Belyaev@cern.ch"
__date__    = "2023-12-06"
__all__     = (
    'PERMUTATOR'   , ## get p-value usig permutations
    'BOOTSTRAPPER' , ## get p-value using bootstrap
    'TOYS'         , ## get p-value using toys     
)
# =============================================================================
from   ostap.core.meta_info     import root_info 
from   ostap.utils.core         import typename
from   ostap.math.math_base     import data2vct 
from   ostap.stats.utils        import weight_trivial , check_all                                           
from   ostap.stats.counters     import EffCounter, ECDF 
from   ostap.utils.progress_bar import progress_bar
import numpy, math, abc 
# =============================================================================
# logging 
# =============================================================================
from ostap.logger.logger import getLogger 
if '__main__' ==  __name__ : logger = getLogger( 'ostap.stats.pvalue' )
else                       : logger = getLogger( __name__ )
# =============================================================================
logger.debug ( 'Utilities to get p-values for Two-Samples & Goodness-of-Fit tests' ) 
# =============================================================================
## Sampling without replacement (Permutations)
def _permutations ( rng , n1 , n2  ) :
    """ Sampling without replacement (Permutations)
    """
    return numpy.split ( rng.permutation ( n1 + n2 ) , [ n1 ] )
# ============================================================================
## Sampling with replacement (Bootstrap)
def _bootstrap   ( rng , n1 , n2 ) :
    """ Sampling with replacement (Bootstrap)
    """
    idx1 = rng.integers ( 0, n1 + n2 , size = n1 )
    idx2 = rng.integers ( 0, n1 + n2 , size = n2 )
    return idx1 , idx2
# ============================================================================
## Resampling generator for datasets (and associated weights)
#  @attention: weights are renormalized such that mean-weights are equal for two samples 
def make_resampling ( sampler     ,
                      N           ,
                      data1       ,
                      data2       , *     ,
                      weight1     = None  ,
                      weight2     = None  ,
                      silent      = True  ,
                      progress    = True  , 
                      random_seed = None  , 
                      description = "Resampling:" ) : 
    """ Yields (data1, data2, weight1, weight2) pairs generated by pooled resampling 
    - ATTENTION:  weights are renormalized such that mean-weights are equal for two samples! 
    """
    if not isinstance ( N , int ) : raise TypeError  ( "Invalid type of `N`: %s" % typename ( N ) )
    if                  N < 1     : raise ValueError ( "Invalid value of `N`: %d" %            N   )

    n1       = len ( data1 )
    n2       = len ( data2 )
    n_total  = n1 + n2

    pooled_x = numpy.concatenate ( [ data1 , data2 ] , axis = 0 )
    pooled_w = None

    w1_trivial = weight_trivial ( weight1 )
    w2_trivial = weight_trivial ( weight2 )
    
    if   w1_trivial and w2_trivial : pass
    else :

        w1mean = 1 if w1_trivial else numpy.mean ( weight1 , dtype = numpy.float64 )
        w2mean = 1 if w2_trivial else numpy.mean ( weight2 , dtype = numpy.float64 )
        scale  = numpy.float32 ( w1mean / w2mean ) 
                
        if   w1_trivial :
            w1_arr   = numpy.ones        ( n1       , dtype = numpy.float32 )
            w2_arr   = numpy.asarray     ( weight2  , dtype = numpy.float32 ) * scale 
        elif w2_trivial :
            w1_arr   = numpy.asarray     ( weight1  ,                      dtype = numpy.float32 )        
            w2_arr   = numpy.full        ( n2       , fill_value = scale , dtype = numpy.float32 )
        else :
            w1_arr   = numpy.asarray     ( weight1  , dtype = numpy.float32 )
            w2_arr   = numpy.asarray     ( weight2  , dtype = numpy.float32 ) * scale 

        pooled_w = numpy.concatenate ( [ w1_arr , w2_arr ] , axis = 0 )
        
    rng = numpy.random.default_rng ( random_seed )

    from ostap.utils.progress_bar import progress_bar
    for _ in progress_bar ( N           ,
                            silent      = silent and not progress ,
                            description = description             ) :
        
        ## the sampling!
        idx1 , idx2 = sampler ( rng , n1 , n2 )

        ds1  = pooled_x [ idx1 ]
        ds2  = pooled_x [ idx2 ]

        w1 , w2 = None , None
        if pooled_w is not None :            
            w1 , w2 = pooled_w [ idx1 ] , pooled_w [ idx2 ]

        yield ds1 , ds2 , w1 , w2

    del pooled_x
    del pooled_w

# =============================================================================
## Helper generator to produce N permutations resamples from pooled datasets under H0
#  1. Pooled dataset is created
#  2. Indices are chosen with replacement for pooled bootstrap
#  3. If present, weights are renormalized to preserve original sample masses
def make_permutations ( N           ,
                        data1       ,
                        data2       , *     ,
                        weight1     = None  ,
                        weight2     = None  ,
                        silent      = True  ,
                        progress    = True  ,
                        random_seed = None  , 
                        description = "Permutations:" ) :
    """ Yields (data1, data2, weight1, weight2) pairs generated by pooled
    resampling with replacement under H0. Preserves the exact initial weight
    sum normalization for both samples.
    """
    return make_resampling ( sampler     = _permutations , 
                             N           = N             ,
                             data1       = data1         ,
                             data2       = data2         ,
                             weight1     = weight1       ,
                             weight2     = weight2       ,
                             silent      = silent        ,
                             progress    = progress      ,
                             random_seed = random_seed   ,
                             description = description   ) 

# =============================================================================
## Helper generator to produce N bootstrap resamples from pooled datasets under H0
#  1. Pooled dataset is created
#  2. Indices are chosen with replacement for pooled bootstrap
#  3. If present, weights are renormalized to preserve original sample masses
def make_bootstrap ( N           ,
                     data1       ,
                     data2       , *     ,
                     weight1     = None  ,
                     weight2     = None  ,
                     silent      = True  ,
                     random_seed = None  , 
                     progress    = True  ,
                     description = "Boostrapping:" ) :
    """ Yields (data1, data2, weight1, weight2) pairs generated by pooled
    resampling with replacement under H0. Preserves the exact initial weight
    sum normalization for both samples.
    """
    return make_resampling ( sampler     = _bootstrap  , 
                             N           = N           ,
                             data1       = data1       ,
                             data2       = data2       ,
                             weight1     = weight1     ,
                             weight2     = weight2     ,
                             silent      = silent      ,
                             progress    = progress    , 
                             random_seed = random_seed ,
                             description = description ) 

    
# =============================================================================
## @class PVALUE
#  Helper base class to run permutation/bootstrap test in parallel
class PVALUE (abc.ABC) :
    """ Helper base class that allows running permutation/bootstrap tests 
    """
    def __init__ ( self        ,
                   gof         ,
                   t_value     ,
                   ds1         ,
                   ds2         ,
                   weight1     = None ,
                   weight2     = None ,
                   random_seed = None ,
                   description = 'Permutations:') :
        
        self.gof     = gof
        self.t_value = t_value
        self.ecdf    = None

        w1_trivial   = weight_trivial ( weight1 )
        w2_trivial   = weight_trivial ( weight2 )

        if w1_trivial and w2_trivial :
            weight1 , weight2 = None, None 

        w1mean = -1000 if w1_trivial else numpy.mean ( weight1 ) 
        w2mean = -1000 if w2_trivial else numpy.mean ( weight2 ) 
        
        self.ds1         = ds1
        self.ds2         = ds2
        self.weight1     = weight1
        self.weight2     = weight2
        self.random_seed = random_seed 
        self.description = description
        
    # =========================================================================
    ## Serialize the object for multiprocessing
    def __getstate__ ( self ) :
        """ Serialize state dictionary without redundant original ds2
        """
        return { 'gof'         : self.gof     ,
                 't_value'     : self.t_value , 
                 'ecdf'        : self.ecdf    ,
                 'ds1'         : self.ds1     ,   
                 'ds2'         : self.ds2     ,   
                 'weight1'     : self.weight1 ,
                 'weight2'     : self.weight2 ,
                 'random_seed' : self.random_seed , 
                 'description' : self.description }
    
    ## De-serialize the object
    def __setstate__ ( self , state ) :
        """ Restore object state from dictionary
        """
        self.gof         = state.pop ( 'gof'         )
        self.t_value     = state.pop ( 't_value'     )
        self.ecdf        = state.pop ( 'ecdf'        )
        self.ds1         = state.pop ( 'ds1'         )
        self.ds2         = state.pop ( 'ds2'         )
        self.weight1     = state.pop ( 'weight1'     )
        self.weight2     = state.pop ( 'weight2'     )
        self.random_seed = state.pop ( 'random_seed' )
        self.description = state.pop ( 'description' )
        
    # =========================================================================
    ## Run N-permutations/boostrapping  on callable execution
    def __call__ ( self , N , silent = True , progress = False ) :
        """ Run N-permutations/boostrapping  on callable execution
        """        
        counter, tvalues = self.run_toys ( N        =  N       ,
                                           silent   = silent   ,
                                           progress = progress )
        
        if not self.ecdf : self.ecdf = ECDF ( tvalues , True )
        else             : self.ecdf.add ( data2vct ( tvalues )  )
        
        return counter, numpy.asarray ( tvalues , dtype = float ) 

    # =========================================================================
    ## Run NN-permutations in parallel using the default ostap' WorkManager
    def run ( self , N , silent = False , progress  = True ) :
        """ Execute permutations/bootstrap in parallel using ostap' WorkManager
        """
        ##
        from ostap.utils.basic  import numcpu
        from ostap.utils.memory import memory_enough
        from ostap.utils.utils  import splitter
        ## 
        me       = math.floor ( memory_enough() ) + 1 
        njobs    = 5 * numcpu () + 1 
        the_list = [ n for n in splitter ( N , njobs ) ] 
        njobs    = len ( the_list ) 

        if not silent : logger.info ( 'GoF p-value: #%d parallel subjobs to be used with WorkManager' %  njobs )
        
        counter = EffCounter()
        tvalues = () 
        
        from ostap.parallel.parallel import WorkManager
        with WorkManager ( silent = silent ) as manager : 
            for result in manager.iexecute ( self.run_toys ,
                                             the_list      ,
                                             block_size    = min ( me , 2 * numcpu() ) , 
                                             progress      = progress         ,
                                             njobs         = njobs            ,
                                             description   = self.description ) :
                cnt , tvals = result 
                counter += cnt
                tvalues += tuple ( float ( t ) for t in tvals )
        
        if not self.ecdf : self.ecdf = ECDF ( tvalues , True )
        else             : self.ecdf.add    ( data2vct ( tvalues )      )
        
        return counter, numpy.asarray ( tvalues , dtype = float ) 
    
    # ========================================================================
    ## Run N-toys/permutatino/bootstrappings/...
    @abc.abstractmethod 
    def run_toys ( self, N , silent = True , progress = False ) :
        """ Run N-toys/permutations/bootstrappings/...
        """
        return NotImplemented

# =============================================================================
## @class PERMUTATOR
#  Helper class to run permutation test in parallel with optional dataset slicing.
class PERMUTATOR (PVALUE) :
    """ Helper class that allows running permutation tests in parallel,
    with support for slicing large datasets (ds2) into sub-samples.
    """
    # =========================================================================
    def __init__ ( self        ,
                   gof         ,
                   t_value     ,
                   ds1         ,
                   ds2         ,
                   weight1     = None ,
                   weight2     = None ,
                   random_seed = None , 
                   description = 'Permutations:' ) :
        
        check_all ( ds1 , ds2, weight1 , weight2 , typename  ( self ) )
        
        super().__init__ ( gof         = gof         ,
                           t_value     = t_value     ,
                           ds1         = ds1         ,
                           ds2         = ds2         ,
                           weight1     = weight1     ,
                           weight2     = weight2     ,
                           random_seed = random_seed , 
                           description = description )
        
    ## Run N permutations 
    def run_toys ( self, N , silent = True , progress = False ) :
        """ Run N permutations 
        """        
        counter = EffCounter()
        tvalues = []

        for data1 , data2 , weight1 , weight2 in make_permutations ( N ,
                                                                     self.ds1                   ,
                                                                     self.ds2                   ,
                                                                     weight1     = self.weight1 ,
                                                                     weight2     = self.weight2 ,
                                                                     progress    = progress     ,   
                                                                     silent      = silent       ,
                                                                     random_seed = self.random_seed ) :
            
            ## Note: normalize = False is required for sliced evaluation
            tv       = self.gof.tvalue ( data1     ,
                                         data2     ,
                                         weight1   = weight1 ,
                                         weight2   = weight2 ,
                                         normalize = False   )
            tv       = float ( tv )
            tvalues.append   ( tv  )
            counter += bool  ( self.t_value <= tv  )
            
        return counter , numpy.asarray ( tvalues , dtype = float )

# =============================================================================
## @class BOOTSTRAPPER
#  Helper class to run bootstrap tests in parallel
class BOOTSTRAPPER (PERMUTATOR) :
    """ Helper class that allows running bootstrap tests in parallel,
    """
    def __init__ ( self        ,
                   gof         ,
                   t_value     ,
                   ds1         ,
                   ds2         ,
                   weight1     = None ,
                   weight2     = None ,
                   random_seed = None ,                    
                   description = 'Bootstrapping:' ) :

        super().__init__ ( gof         = gof         ,
                           t_value     = t_value     ,
                           ds1         = ds1         ,
                           ds2         = ds2         ,
                           weight1     = weight1     ,
                           weight2     = weight2     ,
                           random_seed = random_seed ,                            
                           description = description )

    # =========================================================================
    ## Run N-toys over prepared bootstrap samples
    def run_toys ( self , N , silent = True , progress = False ) :
        """ Run N bootstrap pseudo-experiments (toys) across pre-calculated slices
        """        
        counter = EffCounter()
        tvalues = []
        
        for data1 , data2 , weight1 , weight2 in make_bootstrap ( N           ,
                                                                  self.ds1    ,
                                                                  self.ds2    ,
                                                                  weight1     = self.weight1     ,
                                                                  weight2     = self.weight2     ,
                                                                  progress    = progress         ,   
                                                                  silent      = silent           ,
                                                                  random_seed = self.random_seed ) :
                        
            ## Note: normalize = False is required for sliced evaluation
            tv = self.gof.tvalue ( data1     ,
                                   data2     ,
                                   weight1   = weight1 ,
                                   weight2   = weight2 ,
                                   normalize = False   )
            tvalues.append ( float ( tv ) )

        for tv in tvalues : counter += bool ( self.t_value <= tv  )
        
        return counter , numpy.asarray ( tvalues , dtype = float )
    
# =============================================================================
## @class TOYS
#  Helper class to run toys for Goodness-of-Fit studies 
class TOYS (PVALUE) :
    """ Helper class that allow to run toys in parallel 
    """
    def __init__ ( self    , 
                   gof     , *         , 
                   t_value             ,
                   pdf                 ,
                   Ndata               , 
                   sample      = False ,
                   parameters  = {}    ,
                   random_seed = None  ) :
        
        from ostap.fitting.pdfbasic import APDF1
        if not isinstance ( pdf , APDF1 ) : raise TypeError ( "%s: invaild `pdf` type:%s" % ( typename ( self ) , typename ( pdf ) ) )
        
        
        self.pdf        = pdf
        self.Ndata      = Ndata 
        self.sample     = gof.sample 

        if parameters : self.parameters = parameters
        else          : self.parameters = pdf.dct_params () 

        super().__init__ ( gof         = gof         , 
                           t_value     = t_value     ,
                           ds1         = None        ,
                           ds2         = None        ,
                           random_seed = random_seed ,                                                       
                           description = 'Toys:'     )
        
    # =========================================================================
    ## serialize the object 
    def __getstate__ ( self ) :
        """ Serialize the object
        """
        ## the base 
        state  = super().__getstate__ () 
        
        self.pdf.load_params ( self.parameters , silent = True )
        state [ 'pdf'        ] = self.pdf
        state [ 'Ndata'      ] = self.Ndata
        state [ 'sample'     ] = self.sample 
        state [ 'parameters' ] = self.parameters 
        return state

    # =========================================================================
    ## de-serialize the object 
    def __setstate__ ( self , state ) :
        """ De-serialize the object
        """
        super().__setstate__ ( self , state )
        
        self.pdf         = state.pop ( 'pdf'        )
        self.Ndata       = state.pop ( 'Ndata'      )
        self.sample      = state.pop ( 'sample'     )
        self.parameters  = state.pop ( 'parameters' )

        ## (1) re-load parameters 
        self.pdf.load_params ( self.parameters , silent = True )

    # =========================================================================
    ## run N-toys 
    def run_toys ( self , N , silent = True , progress = False ) :
        """ Run N-toys
        """
        
        seed = self.random_seed
        if not seed : seed = 0
        
        import ROOT 
        ROOT.gRandom                     .SetSeed ( seed ) 
        ROOT.RooRandom.randomGenerator() .SetSeed ( seed )

        counter = EffCounter ()
        tvalues = [] 
        for i in progress_bar ( N , description = self.description , silent = not progress ) : 

            ## for consistency
            self.pdf.load_params ( self.parameters , silent = True )
            
            dset     = self.pdf.generate ( self.Ndata , sample = self.sample )
            tv       = self.gof ( self.pdf , dset )
            counter += bool ( self.t_value > tv   ) ## NOTE THE SIGN HERE!

            tvalues.append ( tv ) 

            if isinstance  ( dset , ROOT.RooDataSet ) :
                dset.clear ()
                ROOT.SetOwnership ( dset , True )
                del dset

        if not self.ecdf : self.ecdf = ECDF ( tvalues  , True ) 
        else             : self.ecdf.add ( data2vct ( tvalues )  )

        return counter, numpy.asarray ( tvalues , dtype = float ) 

# ==============================================================================
if '__main__' == __name__ :
    
    from ostap.utils.docme import docme
    docme ( __name__ , logger = logger )

# =============================================================================
##                                                                      The END 
# =============================================================================
