#!/usr/bin/env bash
. /cvmfs/lhcb.cern.ch/lib/group_login.sh
source /cvmfs/sft.cern.ch/lcg/views/LCG_93/${CMTCONFIG}/setup.sh 
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/ && make -j12 && make install
