#!/usr/bin/env bash
. /cvmfs/lhcb.cern.ch/lib/group_login.sh
source /cvmfs/sft.cern.ch/lcg/views/LCG_93/${CMTCONFIG}/setup.sh
source build/INSTALL/thisostap.sh 
cd build 
ctest -N  && cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/ && ctest -R test_models2_2D
ctest -N  && cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/ && ctest -R test_models2_2D
