#!/usr/bin/env bash
. /cvmfs/lhcb.cern.ch/lib/group_login.sh
export CMTCONFIG=x86_64-slc6-gcc62-opt
source /cvmfs/sft.cern.ch/lcg/views/LCG_93/${CMTCONFIG}/setup.sh
source build/INSTALL/thisostap.sh 
cd build 
ctest -j16  && cmake .. -DCMAKE_INSTALL_PREFIX=./INSTALL/ && ctest -j16
